documentation_target = "gitlab" #generic: common features for markdown wikis
                                #gitlab : enables gitlab wiki specific features

scope = [ "tvm", "cdm", "bdr" ]
skip_model_keys = ["description",
                            "guidelines",
                            "terrain",
                            "tuning",
                            "att&ck",
                            "actors",
                            "vectors",
                            "justification",
                            "chaining",
                            "cve"]

skip_vocabularies = ["mitigation",
                    "logsources",
                    "nist",
                    "att&ck"]

[gitlab]
model_cover_pages = true #Creates a cover page for the model sub-folder
                         #using JSON Tables to facilitate searches
uuid_permalinks = true   #All markdown files are named using UUIDs to create 
                         #a permanent URL link. YAML frontmatter is used for page titles.

[cve]
default_db_link = "https://nvd.nist.gov/vuln/detail/"
retrieve_details = true
proxy = false

[object_names]
tvm = "Threat Vectors"
cdm = "Detection Models"
mdr = "Detection Rules"
bdr = "Business Requests"
rpt = "Intelligence Reports"
lookup_metadata = "Lookup Metadata"

[titles]
tvm = "Threat Vector Schema"
cdm = "Detection Objectives Schema"
mdr = "Detection Rules Schema"
bdr = "Business Detection Schema"

[icons]
tvm = "â˜£ï¸"
cdm = "ğŸ›¡ï¸"
mdr = "ğŸš¨"
bdr = "ğŸ›ï¸"
vocab = "ğŸ“’"
metaschema = "ğŸ—ï¸"
lookups = "ğŸ”"
metadata = "ğŸ—ƒï¸"
lookup_metadata = "ğŸ”£"
id = "ğŸ”‘"
uuid = "ğŸ”‘"
name = "ğŸ«"
title = "ğŸ«"
references = "ğŸ”—"
meta = "âœ"
version = "ğŸ·ï¸"
created = "ğŸ—“ï¸"
modified = "ğŸ—“ï¸"
configurations = "ğŸ› ï¸"
author = "ğŸ‘©â€ğŸ’»"
priority = "â—"
actor = "ğŸ‘¹"
threat = "â˜£ï¸"
detection = "ğŸ›¡ï¸"
alert = "ğŸš¨"
reports = "ğŸ“°"
request = "ğŸ›ï¸"
description = "ğŸ”¬"
affiliations = "ğŸ‘¥"
aliases = "ğŸ€"
guidelines = "ğŸ§ª"
tuning = "ğŸ”§"
terrain = "ğŸ–¥ï¸"
playbook = "ğŸ‘£"
home = "âšœï¸"
misp = "ğŸŒŒ"
stix = "â˜¢ï¸"
cve = "â¤ï¸â€ğŸ©¹"
link = "ğŸ”—"
logsources = "ğŸ“‘"
fields = "ğŸ”–"
atomics = "âš›ï¸"
systems = "ğŸ”©"
subschemas = "ğŸ§©"
tags = "ğŸ·ï¸"
contributors = "ğŸ‘¥"
scheduling = "â²"
timeframe = "â±ï¸"
frequency = "â±"
lookback = "âŒ›"
duration = "âŒ›"
throttling = "ğŸ—œï¸"
threshold = "âš–ï¸"
query = "ğŸ”"

