scope = [ "tam", "tvm", "cdm", "bdr" ]
skip_model_keys = ["description",
                            "guidelines",
                            "aliases",
                            "terrain",
                            "tuning",
                            "att&ck",
                            "actors",
                            "vectors",
                            "justification",
                            "chaining",
                            "cve",
                            "att&ck_groups"]
skip_vocabularies = ["mitigation",
                    "logsources",
                    "nist",
                    "att&ck"]

[cve]
default_db_link = "https://nvd.nist.gov/vuln/detail/"
retrieve_details = true
proxy = false

[wiki]
# Custom wiki link to the generated documentation.
# If generating a Gitlab Wiki, the URL is automatically
# computed from CI Variables
wiki_link = ""

[object_names]
tam = "Threat Actors"
tvm = "Threat Vectors"
cdm = "Detection Models"
mdr = "Detection Rules"
bdr = "Business Requests"
rpt = "Intelligence Reports"
lookup_metadata = "Lookup Metadata"

[titles]
tam = "Threat Actor Models Data Model Reference"
tvm = "Threat Vector Models Data Model Reference"
cdm = "Cyber Detection Models Data Model Reference"
mdr = "Managed Detection Rules Data Model Reference"
bdr = "Business Detection Rules Data Model Reference"

[icons]
tam = "ğŸ‘º"
tvm = "â˜£ï¸"
cdm = "ğŸ›¡ï¸"
mdr = "ğŸš¨"
bdr = "ğŸ›ï¸"
vocab = "ğŸ“’"
metaschema = "ğŸ—ï¸"
lookups = "ğŸ”"
metadata = "ğŸ—ƒï¸"
lookup_metadata = "ğŸ”£"
id = "ğŸ”‘"
uuid = "ğŸ”‘"
name = "ğŸ«"
title = "ğŸ«"
references = "ğŸ”—"
meta = "âœ"
version = "ğŸ·ï¸"
created = "ğŸ—“ï¸"
modified = "ğŸ—“ï¸"
configurations = "ğŸ› ï¸"
author = "ğŸ‘©â€ğŸ’»"
priority = "â—"
actor = "ğŸ‘¹"
threat = "â˜£ï¸"
detection = "ğŸ›¡ï¸"
alert = "ğŸš¨"
reports = "ğŸ“°"
request = "ğŸ›ï¸"
description = "ğŸ”¬"
affiliations = "ğŸ‘¥"
aliases = "ğŸ€"
guidelines = "ğŸ§ª"
tuning = "ğŸ”§"
terrain = "ğŸ–¥ï¸"
playbook = "ğŸ‘£"
home = "âšœï¸"
misp = "ğŸŒŒ"
stix = "â˜¢ï¸"
cve = "â¤ï¸â€ğŸ©¹"
link = "ğŸ”—"
logsources = "ğŸ“‘"
fields = "ğŸ”–"
atomics = "âš›ï¸"
systems = "ğŸ”©"
subschemas = "ğŸ§©"
tags = "ğŸ·ï¸"
contributors = "ğŸ‘¥"
scheduling = "â²"
timeframe = "â±ï¸"
frequency = "â±"
lookback = "âŒ›"
duration = "âŒ›"
throttling = "ğŸ—œï¸"
threshold = "âš–ï¸"
query = "ğŸ”"

[indexes]
tam = "Threat Actors Navigation Index"
tvm = "Threat Vectors Navigation Index"
cdm = "Detection Models Navigation Index"
bdr = "Business Detection Requests Navigation Index"
mdr = "Detection Rules Navigation Index"

